language: php

php:
  - 7.0
  - 7.1
  - 7.2

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev
  - php artisan key:generate
  - php artisan migrate

before_install:
  - mysql -e 'CREATE DATABASE realworld_test;'

script:
  - vendor/bin/phpunit

services:
  - mysql

notifications:
  email:
    recipients:
      - minkaung.htet@mm-digital-solutions.com
    on_success: always # default: change
    on_failure: always